include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - android/**
    - build/**
    - ios/**
    - linux/**
    - macos/**
    - web/**
    - windows/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    directives_ordering: error
    public_member_api_docs: error

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - await_only_futures
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - public_member_api_docs
    - unawaited_futures
